# Generated by Django 3.2.23 on 2024-01-10 23:41

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerArcFeatureService',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layers.layer')),
                ('mouseover_field', models.CharField(blank=True, default=None, help_text='feature level attribute used in mouseover display', max_length=75, null=True)),
                ('custom_style', models.CharField(blank=True, choices=[(None, '------'), ('color', 'color'), ('random', 'random')], default=None, help_text="Apply a custom styling rule: i.e. 'color' for Native-Land.ca layers, or 'random' to assign arbitary colors", max_length=255, null=True)),
                ('vector_outline_width', models.IntegerField(blank=True, default=None, null=True, verbose_name='Vector Stroke Width')),
                ('vector_outline_color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=[('#FFFFFF', 'white'), ('#888888', 'gray'), ('#000000', 'black'), ('#FF0000', 'red'), ('#FFFF00', 'yellow'), ('#00FF00', 'green'), ('#00FFFF', 'cyan'), ('#0000FF', 'blue'), ('#FF00FF', 'magenta')], verbose_name='Vector Stroke Color')),
                ('vector_outline_opacity', models.FloatField(blank=True, default=None, null=True, verbose_name='Vector Stroke Opacity')),
                ('vector_fill', models.FloatField(blank=True, default=None, null=True, verbose_name='Vector Fill Opacity')),
                ('vector_color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=[('#FFFFFF', 'white'), ('#888888', 'gray'), ('#000000', 'black'), ('#FF0000', 'red'), ('#FFFF00', 'yellow'), ('#00FF00', 'green'), ('#00FFFF', 'cyan'), ('#0000FF', 'blue'), ('#FF00FF', 'magenta')], verbose_name='Vector Fill Color')),
                ('point_radius', models.IntegerField(blank=True, default=None, help_text='Used only for for Point layers (default is 2)', null=True)),
                ('vector_graphic', models.CharField(blank=True, default=None, help_text='address of image to use for point data', max_length=255, null=True, verbose_name='Vector Graphic')),
                ('vector_graphic_scale', models.FloatField(blank=True, default=True, help_text='Scale for the vector graphic from original size.', null=True, verbose_name='Vector Graphic Scale')),
                ('opacity', models.FloatField(blank=True, default=0.5, null=True, verbose_name='Initial Opacity')),
                ('arcgis_layers', models.CharField(blank=True, help_text='comma separated list of arcgis layer IDs', max_length=255, null=True)),
                ('password_protected', models.BooleanField(default=False, help_text='check this if the server requires a password to show layers')),
                ('disable_arcgis_attributes', models.BooleanField(default=False, help_text='Click to disable clickable ArcRest layers')),
            ],
            options={
                'abstract': False,
            },
            bases=('layers.layer',),
        ),
        migrations.CreateModel(
            name='LayerArcREST',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layers.layer')),
                ('query_by_point', models.BooleanField(default=False, help_text='Do not buffer selection clicks (not recommended for point or line data)')),
                ('arcgis_layers', models.CharField(blank=True, help_text='comma separated list of arcgis layer IDs', max_length=255, null=True)),
                ('password_protected', models.BooleanField(default=False, help_text='check this if the server requires a password to show layers')),
                ('disable_arcgis_attributes', models.BooleanField(default=False, help_text='Click to disable clickable ArcRest layers')),
            ],
            options={
                'abstract': False,
            },
            bases=('layers.layer',),
        ),
        migrations.CreateModel(
            name='LayerVector',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layers.layer')),
                ('mouseover_field', models.CharField(blank=True, default=None, help_text='feature level attribute used in mouseover display', max_length=75, null=True)),
                ('custom_style', models.CharField(blank=True, choices=[(None, '------'), ('color', 'color'), ('random', 'random')], default=None, help_text="Apply a custom styling rule: i.e. 'color' for Native-Land.ca layers, or 'random' to assign arbitary colors", max_length=255, null=True)),
                ('vector_outline_width', models.IntegerField(blank=True, default=None, null=True, verbose_name='Vector Stroke Width')),
                ('vector_outline_color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=[('#FFFFFF', 'white'), ('#888888', 'gray'), ('#000000', 'black'), ('#FF0000', 'red'), ('#FFFF00', 'yellow'), ('#00FF00', 'green'), ('#00FFFF', 'cyan'), ('#0000FF', 'blue'), ('#FF00FF', 'magenta')], verbose_name='Vector Stroke Color')),
                ('vector_outline_opacity', models.FloatField(blank=True, default=None, null=True, verbose_name='Vector Stroke Opacity')),
                ('vector_fill', models.FloatField(blank=True, default=None, null=True, verbose_name='Vector Fill Opacity')),
                ('vector_color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=[('#FFFFFF', 'white'), ('#888888', 'gray'), ('#000000', 'black'), ('#FF0000', 'red'), ('#FFFF00', 'yellow'), ('#00FF00', 'green'), ('#00FFFF', 'cyan'), ('#0000FF', 'blue'), ('#FF00FF', 'magenta')], verbose_name='Vector Fill Color')),
                ('point_radius', models.IntegerField(blank=True, default=None, help_text='Used only for for Point layers (default is 2)', null=True)),
                ('vector_graphic', models.CharField(blank=True, default=None, help_text='address of image to use for point data', max_length=255, null=True, verbose_name='Vector Graphic')),
                ('vector_graphic_scale', models.FloatField(blank=True, default=True, help_text='Scale for the vector graphic from original size.', null=True, verbose_name='Vector Graphic Scale')),
                ('opacity', models.FloatField(blank=True, default=0.5, null=True, verbose_name='Initial Opacity')),
            ],
            options={
                'abstract': False,
            },
            bases=('layers.layer',),
        ),
        migrations.CreateModel(
            name='LayerWMS',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layers.layer')),
                ('query_by_point', models.BooleanField(default=False, help_text='Do not buffer selection clicks (not recommended for point or line data)')),
                ('wms_help', models.BooleanField(default=False, help_text='Enable simple selection for WMS fields. Only supports WMS 1.1.1')),
                ('wms_slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='WMS Layer Name')),
                ('wms_version', models.CharField(blank=True, choices=[(None, ''), ('1.0.0', '1.0.0'), ('1.1.0', '1.1.0'), ('1.1.1', '1.1.1'), ('1.3.0', '1.3.0')], default=None, help_text='WMS Versioning - usually either 1.1.1 or 1.3.0', max_length=10, null=True)),
                ('wms_format', models.CharField(blank=True, default=None, help_text='most common: image/png. Only image types supported.', max_length=100, null=True, verbose_name='WMS Format')),
                ('wms_srs', models.CharField(blank=True, default=None, help_text='If not EPSG:3857 WMS requests will be proxied', max_length=100, null=True, verbose_name='WMS SRS')),
                ('wms_timing', models.CharField(blank=True, default=None, help_text='http://docs.geoserver.org/stable/en/user/services/wms/time.html#specifying-a-time', max_length=255, null=True, verbose_name='WMS Time')),
                ('wms_time_item', models.CharField(blank=True, default=None, help_text='Time Attribute Field, if different from "TIME". Proxy only.', max_length=255, null=True, verbose_name='WMS Time Field')),
                ('wms_styles', models.CharField(blank=True, default=None, help_text='pre-determined styles, if exist', max_length=255, null=True, verbose_name='WMS Styles')),
                ('wms_additional', models.TextField(blank=True, default=None, help_text='additional WMS key-value pairs: &key=value...', null=True, verbose_name='WMS Additional Fields')),
                ('wms_info', models.BooleanField(default=False, help_text='enable Feature Info requests on click')),
                ('wms_info_format', models.CharField(blank=True, default=None, help_text='Available supported feature info formats', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('layers.layer',),
        ),
        migrations.CreateModel(
            name='LayerXYZ',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layers.layer')),
                ('query_by_point', models.BooleanField(default=False, help_text='Do not buffer selection clicks (not recommended for point or line data)')),
            ],
            options={
                'abstract': False,
            },
            bases=('layers.layer',),
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layers.layer')),
                ('search_query', models.BooleanField(default=False, help_text='Select when layers are queryable - e.g. MDAT and CAS')),
            ],
            bases=('layers.layer',),
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='layer',
            name='attribute_event',
            field=models.CharField(choices=[('click', 'click'), ('mouseover', 'mouseover')], default='click', max_length=35),
        ),
        migrations.AddField(
            model_name='layer',
            name='bookmark',
            field=models.CharField(blank=True, help_text='link to view data layer in the planner', max_length=755, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='catalog_id',
            field=models.TextField(blank=True, help_text='unique ID of associated record in catalog', null=True, verbose_name='Catalog Record Id'),
        ),
        migrations.AddField(
            model_name='layer',
            name='catalog_name',
            field=models.TextField(blank=True, help_text='name of associated record in catalog', null=True, verbose_name='Catalog Record Name'),
        ),
        migrations.AddField(
            model_name='layer',
            name='compress_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layer',
            name='data_download',
            field=models.CharField(blank=True, help_text='link to download the data', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='data_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='data_overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='data_publish_date',
            field=models.DateField(blank=True, default=None, help_text='YYYY-MM-DD', null=True, verbose_name='Date published'),
        ),
        migrations.AddField(
            model_name='layer',
            name='data_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='disabled_message',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='espis_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layer',
            name='espis_region',
            field=models.CharField(blank=True, choices=[('Mid Atlantic', 'Mid Atlantic')], default=None, help_text='Region to search within', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='espis_search',
            field=models.CharField(blank=True, default=None, help_text='keyphrase search for ESPIS Link', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='geoportal_id',
            field=models.CharField(blank=True, default=None, help_text='GeoPortal UUID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='is_annotated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layer',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='when disabled, the layer will still appear in the TOC, only disabled'),
        ),
        migrations.AddField(
            model_name='layer',
            name='kml',
            field=models.CharField(blank=True, help_text='link to download the KML', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='label_field',
            field=models.CharField(blank=True, help_text='Which field should be used for labels and feature identification in reports?', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('XYZ', 'XYZ'), ('WMS', 'WMS'), ('ArcRest', 'ArcRest'), ('ArcFeatureServer', 'ArcFeatureServer'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('Vector', 'Vector'), ('VectorTile', 'VectorTile'), ('placeholder', 'placeholder')], default='ArcRest', help_text='use placeholder to temporarily remove layer from TOC', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='learn_more',
            field=models.CharField(blank=True, default=None, help_text='link to view description in the Learn section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='legend',
            field=models.CharField(blank=True, help_text='URL or path to the legend image file', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='legend_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='legend_title',
            field=models.CharField(blank=True, help_text='alternative to using the layer name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='lookup_field',
            field=models.CharField(blank=True, help_text='To override the style based on specific attributes, provide the attribute name here and define your attributes in the Lookup table below.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='map_tiles',
            field=models.CharField(blank=True, help_text='internal link to a page that details how others might consume the data', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='maxZoom',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Maximum zoom'),
        ),
        migrations.AddField(
            model_name='layer',
            name='metadata',
            field=models.CharField(blank=True, help_text='link to view/download the metadata', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='minZoom',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Minimum zoom'),
        ),
        migrations.AddField(
            model_name='layer',
            name='proxy_url',
            field=models.BooleanField(default=False, help_text='proxy layer url through marine planner'),
        ),
        migrations.AddField(
            model_name='layer',
            name='shareable_url',
            field=models.BooleanField(default=True, help_text='Indicates whether the data layer (e.g. map tiles) can be shared with others (through the Map Tiles Link)'),
        ),
        migrations.AddField(
            model_name='layer',
            name='show_legend',
            field=models.BooleanField(default=True, help_text='show the legend for this layer if available'),
        ),
        migrations.AddField(
            model_name='layer',
            name='slug_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='source',
            field=models.CharField(blank=True, help_text='link back to the data source', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='parent_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_themes', to='layers.theme'),
        ),
        migrations.CreateModel(
            name='ChildOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='layers.theme')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
