# Generated by Django 3.2.23 on 2024-01-05 04:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerArcGIS',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layers.layer')),
                ('arcgis_layers', models.CharField(blank=True, help_text='comma separated list of arcgis layer IDs', max_length=255, null=True)),
                ('password_protected', models.BooleanField(default=False, help_text='check this if the server requires a password to show layers')),
                ('query_by_point', models.BooleanField(default=False, help_text='Do not buffer selection clicks (not recommended for point or line data)')),
                ('disable_arcgis_attributes', models.BooleanField(default=False, help_text='Click to disable clickable ArcRest layers')),
            ],
            bases=('layers.layer',),
        ),
        migrations.CreateModel(
            name='LayerWMS',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layers.layer')),
                ('wms_slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='WMS Layer Name')),
                ('wms_version', models.CharField(blank=True, choices=[(None, ''), ('1.0.0', '1.0.0'), ('1.1.0', '1.1.0'), ('1.1.1', '1.1.1'), ('1.3.0', '1.3.0')], default=None, help_text='WMS Versioning - usually either 1.1.1 or 1.3.0', max_length=10, null=True)),
                ('wms_format', models.CharField(blank=True, default=None, help_text='most common: image/png. Only image types supported.', max_length=100, null=True, verbose_name='WMS Format')),
                ('wms_srs', models.CharField(blank=True, default=None, help_text='If not EPSG:3857 WMS requests will be proxied', max_length=100, null=True, verbose_name='WMS SRS')),
                ('wms_timing', models.CharField(blank=True, default=None, help_text='http://docs.geoserver.org/stable/en/user/services/wms/time.html#specifying-a-time', max_length=255, null=True, verbose_name='WMS Time')),
                ('wms_time_item', models.CharField(blank=True, default=None, help_text='Time Attribute Field, if different from "TIME". Proxy only.', max_length=255, null=True, verbose_name='WMS Time Field')),
                ('wms_styles', models.CharField(blank=True, default=None, help_text='pre-determined styles, if exist', max_length=255, null=True, verbose_name='WMS Styles')),
                ('wms_additional', models.TextField(blank=True, default=None, help_text='additional WMS key-value pairs: &key=value...', null=True, verbose_name='WMS Additional Fields')),
                ('wms_info', models.BooleanField(default=False, help_text='enable Feature Info requests on click')),
                ('wms_info_format', models.CharField(blank=True, default=None, help_text='Available supported feature info formats', max_length=255, null=True)),
            ],
            bases=('layers.layer',),
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='layer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='parent_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_themes', to='layers.theme'),
        ),
        migrations.CreateModel(
            name='SubthemeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('child_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.theme')),
                ('parent_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtheme_order', to='layers.theme')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LayerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.layer')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.theme')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChildOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='layers.theme')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
