# Generated by Django 3.2.23 on 2024-02-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0002_auto_20240214_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='layer_type',
            new_name='theme_type',
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('XYZ', 'XYZ'), ('WMS', 'WMS'), ('ArcRest', 'ArcRest'), ('ArcFeatureServer', 'ArcFeatureServer'), ('Vector', 'Vector'), ('VectorTile', 'VectorTile'), ('placeholder', 'placeholder')], help_text='use placeholder to temporarily remove layer from TOC', max_length=50),
        ),
    ]
