# Generated by Django 3.2.12 on 2024-03-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0002_auto_20240328_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='old_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
