# Generated by Django 3.2.12 on 2024-04-08 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0002_auto_20240408_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilayerassociation',
            name='parentLayer',
            field=models.ForeignKey(db_column='parentlayer', on_delete=django.db.models.deletion.CASCADE, related_name='parent_layer', to='layers.layer'),
        ),
    ]
