# Generated by Django 3.2.12 on 2024-05-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0003_alter_multilayerassociation_parentlayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerarcfeatureservice',
            name='opacity',
        ),
        migrations.RemoveField(
            model_name='layervector',
            name='opacity',
        ),
        migrations.AddField(
            model_name='layer',
            name='opacity',
            field=models.FloatField(blank=True, default=0.5, null=True, verbose_name='Initial Opacity'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme_type',
            field=models.CharField(blank=True, choices=[('radio', 'radio'), ('checkbox', 'checkbox')], help_text='use placeholder to temporarily remove layer from TOC', max_length=50),
        ),
    ]
