# Generated by Django 3.2.23 on 2024-02-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0003_auto_20240207_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='layer_type',
            field=models.CharField(blank=True, choices=[('radio', 'radio'), ('checkbox', 'checkbox')], help_text='use placeholder to temporarily remove layer from TOC', max_length=50),
        ),
    ]
