# Generated by Django 3.2.12 on 2024-03-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0003_theme_old_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='old_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
