# Generated by Django 3.2.12 on 2024-05-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0004_auto_20240503_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='data_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='data_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='disabled_message',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='source',
            field=models.CharField(blank=True, help_text='link back to the data source', max_length=255, null=True),
        ),
    ]
