# Generated by Django 3.2.12 on 2024-05-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0005_auto_20240504_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='learn_more',
            field=models.CharField(blank=True, default=None, help_text='MDAT/VTR/CAS: link to learn more', max_length=255, null=True),
        ),
    ]
