# Generated by Django 3.2.12 on 2024-05-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0006_theme_learn_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='legend',
            field=models.CharField(blank=True, help_text='URL or path to the legend image file', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='legend_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='legend_title',
            field=models.CharField(blank=True, help_text='alternative to using the layer name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='show_legend',
            field=models.BooleanField(default=True, help_text='show the legend for this layer if available'),
        ),
    ]
