# Generated by Django 3.2.12 on 2024-05-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0007_auto_20240508_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='data_download',
            field=models.CharField(blank=True, help_text='link to download the data', max_length=255, null=True),
        ),
    ]
