# Generated by Django 3.2.12 on 2024-05-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0009_auto_20240509_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childorder',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
    ]
