# Generated by Django 3.2.12 on 2024-05-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0010_auto_20240520_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='search_query',
            field=models.BooleanField(default=False, help_text='Select when layers are queryable - e.g. MDAT and CAS'),
        ),
        migrations.DeleteModel(
            name='Library',
        ),
    ]
