# Generated by Django 3.2.12 on 2024-05-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0011_auto_20240520_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='lookup_field',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='lookup_table',
        ),
        migrations.AddField(
            model_name='layerarcfeatureservice',
            name='lookup_field',
            field=models.CharField(blank=True, help_text='To override the style based on specific attributes, provide the attribute name here and define your attributes in the Lookup table below.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layerarcfeatureservice',
            name='lookup_table',
            field=models.ManyToManyField(blank=True, to='layers.LookupInfo'),
        ),
        migrations.AddField(
            model_name='layervector',
            name='lookup_field',
            field=models.CharField(blank=True, help_text='To override the style based on specific attributes, provide the attribute name here and define your attributes in the Lookup table below.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layervector',
            name='lookup_table',
            field=models.ManyToManyField(blank=True, to='layers.LookupInfo'),
        ),
    ]
