# Generated by Django 3.2.25 on 2024-06-04 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0012_auto_20240524_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerarcfeatureservice',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.layer', unique=True),
        ),
        migrations.AlterField(
            model_name='layerarcrest',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.layer', unique=True),
        ),
        migrations.AlterField(
            model_name='layervector',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.layer', unique=True),
        ),
        migrations.AlterField(
            model_name='layerwms',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.layer', unique=True),
        ),
        migrations.AlterField(
            model_name='layerxyz',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.layer', unique=True),
        ),
    ]
