# Generated by Django 3.2.12 on 2024-08-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0013_auto_20240604_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='is_dynamic',
            field=models.BooleanField(default=False),
        ),
    ]
