# Generated by Django 3.2.12 on 2024-08-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0014_theme_is_dynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='dynamic_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
