# Generated by Django 3.2.12 on 2024-09-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0015_theme_dynamic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='default_keyword',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='placeholder_text',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
