# Generated by Django 3.2.12 on 2024-09-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0016_auto_20240904_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='default_keyword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='placeholder_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
