# Generated by Django 3.2.25 on 2025-01-31 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('layers', '0017_auto_20240906_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='is_top_theme',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='childorder',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'layers'), ('model', 'theme')), models.Q(('app_label', 'layers'), ('model', 'layer')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Child Type'),
        ),
        migrations.AlterField(
            model_name='childorder',
            name='parent_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_theme', to='layers.theme'),
        ),
    ]
