# Generated by Django 3.2.25 on 2025-01-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0019_auto_20250131_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='is_top_theme',
            field=models.BooleanField(default=False, help_text='Check this box to show this level at the top tier of the layer picker', verbose_name='Is Top Level Theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='order',
            field=models.PositiveIntegerField(default=10, help_text="Only used for 'Top Level Themes'", verbose_name='Default Order'),
        ),
    ]
