# Generated by Django 3.2.25 on 2025-01-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0020_auto_20250131_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(help_text='e.g.: "Grandparent|Parent|Name". Spaces are allowed.', max_length=255, verbose_name='System Name'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme_type',
            field=models.CharField(blank=True, choices=[('radio', 'radio: select 1 layer at a time'), ('checkbox', 'checkbox: support simultaneous layers')], default='checkbox', help_text='This only impacts how many LAYERS can be activated at once. This does not impact child-themes or their layers', max_length=50),
        ),
    ]
