# Generated by Django 3.2.25 on 2025-02-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0021_auto_20250131_2126'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='childorder',
            index=models.Index(fields=['id'], name='layers_chil_id_b325cd_idx'),
        ),
        migrations.AddIndex(
            model_name='childorder',
            index=models.Index(fields=['parent_theme'], name='layers_chil_parent__becea0_idx'),
        ),
        migrations.AddIndex(
            model_name='childorder',
            index=models.Index(fields=['content_type'], name='layers_chil_content_13302b_idx'),
        ),
        migrations.AddIndex(
            model_name='layer',
            index=models.Index(fields=['id'], name='layers_laye_id_228d74_idx'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['id'], name='layers_them_id_f874c8_idx'),
        ),
    ]
