# Generated by Django 4.2.20 on 2025-04-08 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0023_alter_layer_site_alter_theme_site'),
        ('layers', '0023_layer_last_http_status_layer_last_success_status_and_more'),
    ]

    operations = [
    ]
