# Generated by Django 4.2.20 on 2025-04-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0024_alter_layer_site_alter_theme_site'),
        ('layers', '0024_merge_20250408_2111'),
    ]

    operations = [
    ]
