# Generated by Django 4.2.20 on 2025-04-23 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0023_auto_20250423_0004'),
        ('layers', '0024_merge_20250408_2111'),
    ]

    operations = [
    ]
