# Generated by Django 4.2.23 on 2025-08-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0025_merge_20250423_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='metadata_url',
            field=models.CharField(blank=True, help_text='link to the metadata', max_length=255, null=True, verbose_name='Metadata URL'),
        ),
    ]
