# Generated by Django 4.2.23 on 2025-10-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0026_theme_metadata_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='data_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source Name'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='source',
            field=models.CharField(blank=True, help_text='link back to the data source', max_length=255, null=True, verbose_name='Source URL'),
        ),
    ]
