# Generated by Django 4.2.30 on 2026-09-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0027_alter_theme_data_source_alter_theme_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeinfo',
            name='field_label',
            field=models.CharField(blank=True, default=None, help_text='How this entry should be labeled in the map reports', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attributeinfo',
            name='display_name',
            field=models.CharField(blank=True, help_text='How this record will be shown for selection in the admin dashboard', max_length=255, null=True, verbose_name='Record Name'),
        ),
    ]
