name: Django CI

on:
  push:
    branches: [ "main", "ci_testing" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ci_testing/test_requirements.txt
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        coverage run --source='.' ci_testing/mp_layers_testing/manage.py test layers.tests.test_models
        COV=`coverage report --format=total`
        echo "{'coverage':$COV}" > /tmp/coverage_badge.json
    - name: Archive test coverage results
      uses: actions/upload-artifact@v4
      with:
        name: test-coverage-report
        path: /tmp/coverage_badge.json

